### ISSUE TITLE
Implement loop and dominator tree analyses

### ISSUE THREAD

**Issue by bitwalker** [0xPolygonMiden/miden-ir#6]
In order to convert Miden IR to Miden Assembly, we require two analysis passes over the IR which give us the necessary information to transform low-level control flow (primitive branches/jumps) into the higher-level control flow (if/while/repeat) used by Miden Assembly.

- [x] The dominator tree analysis is the foundation on which we build our control flow analyses. This analysis is critical for determining what blocks are involved in a given control flow path, and how control enters/exits that path. It is a low level analysis used by others we will build.
- [x] The loop analysis builds on the dominator tree to recognize loops and their various forms. This analysis will be used as the basis for our transformation of loop-like control flow to Miden Assembly.

There are other analyses/passes related to these that we will implement or may want to implement, but these two are critical for other work in the pipeline.

**Comment by grjte** [comment]
@bitwalker is this closed by https://github.com/0xPolygonMiden/miden-ir/commit/45e1b2265fb4916d7126d63ac0e581b2679e2ddd?

**Comment by bitwalker** [comment]
@grjte Yes, thanks for the reminder!
